-- Wallet balance and deposits support

-- 1) Add wallet_balance to profiles (or users profile table). Use profiles if present; fallback to users.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'wallet_balance'
    ) THEN
      ALTER TABLE public.profiles ADD COLUMN wallet_balance numeric(15,2) NOT NULL DEFAULT 0;
    END IF;
  ELSIF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'wallet_balance'
    ) THEN
      ALTER TABLE public.users ADD COLUMN wallet_balance numeric(15,2) NOT NULL DEFAULT 0;
    END IF;
  END IF;
END $$;

-- 2) Deposits table
CREATE TABLE IF NOT EXISTS public.deposits (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  amount numeric(15,2) not null check (amount > 0),
  currency text not null default 'usd',
  stripe_session_id text,
  stripe_payment_intent text,
  status text not null default 'pending', -- pending, succeeded, failed
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3) Simple RLS (optional) - allow users to read their deposits
ALTER TABLE public.deposits ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='deposits' AND policyname='deposits_select_own'
  ) THEN
    CREATE POLICY deposits_select_own ON public.deposits FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='deposits' AND policyname='deposits_insert_self'
  ) THEN
    CREATE POLICY deposits_insert_self ON public.deposits FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- 4) Update updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS deposits_set_updated_at ON public.deposits;
CREATE TRIGGER deposits_set_updated_at
BEFORE UPDATE ON public.deposits
FOR EACH ROW EXECUTE FUNCTION set_updated_at();


