-- Wallet transactions, stripe_events idempotency, and credit_wallet RPC

-- 1) wallet_transactions table
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  amount_cents bigint not null, -- positive for credit, negative for debit
  currency text not null default 'usd',
  type text not null, -- deposit, refund, purchase, adjustment
  ref text, -- external reference (e.g., Stripe PI id)
  created_at timestamptz default now()
);

ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='wallet_transactions' AND policyname='wallet_tx_select_own'
  ) THEN
    CREATE POLICY wallet_tx_select_own ON public.wallet_transactions FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

-- 2) stripe_events (idempotency log)
CREATE TABLE IF NOT EXISTS public.stripe_events (
  id text primary key,
  type text not null,
  created_at timestamptz default now()
);

-- 3) credit_wallet RPC (atomic)
CREATE OR REPLACE FUNCTION public.credit_wallet(p_user_id uuid, p_amount_cents bigint, p_ref text, p_currency text default 'usd')
RETURNS void AS $$
DECLARE
  v_exists boolean;
BEGIN
  IF p_amount_cents <= 0 THEN
    RAISE EXCEPTION 'Amount must be positive';
  END IF;

  -- Update balance on profiles or users table depending on which exists
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='profiles' AND column_name='wallet_balance') THEN
    UPDATE public.profiles
    SET wallet_balance = COALESCE(wallet_balance, 0) + (p_amount_cents::numeric / 100.0)
    WHERE id = p_user_id;
  ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='users' AND column_name='wallet_balance') THEN
    UPDATE public.users
    SET wallet_balance = COALESCE(wallet_balance, 0) + (p_amount_cents::numeric / 100.0)
    WHERE id = p_user_id;
  ELSE
    RAISE EXCEPTION 'No wallet_balance column found on profiles or users';
  END IF;

  INSERT INTO public.wallet_transactions(user_id, amount_cents, currency, type, ref)
  VALUES (p_user_id, p_amount_cents, p_currency, 'deposit', p_ref);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


