-- Production cleanup: future weekly_leaderboard rows + is_latest correction.
-- Revoke legacy generate_weekly_leaderboard_exact_v2 from clients (wrong semantics:
-- uses current profile wallet/portfolio as "end" values; leaderboard is generated by Netlify TS).
BEGIN;

-- Prevent anon/authenticated from invoking legacy RPC (app uses table + get_weekly_leaderboard_current)
REVOKE ALL ON FUNCTION public.generate_weekly_leaderboard_exact_v2(timestamp with time zone, timestamp with time zone) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generate_weekly_leaderboard_exact_v2(timestamp with time zone, timestamp with time zone) FROM anon;
REVOKE ALL ON FUNCTION public.generate_weekly_leaderboard_exact_v2(timestamp with time zone, timestamp with time zone) FROM authenticated;

-- Drop invalid rows: week not finished yet → start/end snapshots identical, deposits always 0 in UI
DELETE FROM public.weekly_leaderboard WHERE week_end > NOW();

-- Exactly one completed week marked latest (by latest week_end)
UPDATE public.weekly_leaderboard SET is_latest = false;

WITH latest AS (
  SELECT week_start, week_end
  FROM public.weekly_leaderboard
  WHERE week_end <= NOW()
  ORDER BY week_end DESC
  LIMIT 1
)
UPDATE public.weekly_leaderboard wl
SET is_latest = true
FROM latest
WHERE wl.week_start = latest.week_start AND wl.week_end = latest.week_end;

COMMIT;
